### ISSUE TITLE
Running dpkg --configure -a as a standalone command is not that useful

### ISSUE THREAD

**Issue by tersmitten** [Oefenweb/ansible-apt#22]
Maybe only run it after a failed `apt-get dist-upgrade`?

Any input on this @kvz?

**Comment by kvz** [comment]
In my opinion it should be ran before any apt operations, its purpose is to fix a previous run's errors, so that the upcoming run can do as was instructed.

It's a pragmatic approach, but ever since Ubuntu Breezy, this has served me well to get apt to a consistent state, and never caused me any problems (yet 😄):

```bash
env DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical sudo -HE dpkg --configure -a
env DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical sudo -HE apt-get --option Dpkg::Options::=--force-confold -q -y --force-yes install -f
```
